#define MEMORY_SIZE 4096
#define STACK_SIZE 16
#define KEYPAD_SIZE 16
#define DISPLAY_HEIGHT 32
#define DISPLAY_WIDTH 64
#define DISPLAY_SIZE DISPLAY_HEIGHT*DISPLAY_WIDTH
#define KEYPAD_SIZE 16
#define SCREEN_HEIGHT 480
#define SCREEN_WIDTH 640
#define TICKS 60 // Hz framerate